import {
  ArrowLeft,
  Bookmark,
  EllipsisVertical,
  Grid3x2,
  Heart,
  House,
  Menu,
  MessageCircle,
  Plus,
  Search,
  Send,
  SquareUser,
  TvMinimalPlay,
} from 'lucide-react-native';

export const Icons = {
  HouseIcon: House,
  ReelsIcon: TvMinimalPlay,
  SearchIcon: Search,
  SendIcon: Send,
  PlusIcon: Plus,
  HeartIcon: Heart,
  ArrowLeftIcon: ArrowLeft,
  CommentIcon: MessageCircle,
  BookmarkIcon: Bookmark,
  ThreeDotsIcon: EllipsisVertical,
  GridIcon: Grid3x2,
  UserIcon: SquareUser,
  MenuIcon: Menu,
};
